generator:
  class: sfDoctrineGenerator
  param:
    model_class:           OrdemServico
    theme:                 adminia
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                Ordens de Serviço
    route_prefix:          ordem_servico
    with_doctrine_route:   true
    actions_base_class:    sfActions
    icon:                 "fa fa-file-text"

    config:
      actions: ~
      fields:
        created_at:      { label: Data de Criação }
        updated_at:      { label: Data de Modificação }
        pago:            { label: Pgto Efetuado }
        troca:           { label: Troca de Peça }
        recorrente:      { label: É Recorrente }
        testado:         { label: Aparelho Testado? }
        imei:            { label: IMEI }
        mensagem_impressao: { label: Mensagem na impressão }
        com_senha: { label: Senha? }
      list:
        title:          Ordens de Serviço
        display:        [id, created_at, updated_at, valor, status]
        sort:           ~
        batch_actions:  []
        object_actions:
          show: { label: Ver }
          _edit: { label: Editar }
        actions:
          _new: { label: "Nova"}
      filter:
          display: [modelo_defeito_id, cliente_id, pagamento, pago, troca, recorrente, testado, imei, data_retirada, status]
      form:
        display: [modelo_defeito_id, cliente_id, comentario, pagamento, valor, preco_dinheiro, preco_cartao, pago, troca, recorrente, testado, imei, com_senha, senha, garantia, data_retirada, status, mensagem_impressao]
      edit:
        title: Editando OS
        actions:
          _save: { label: Salvar }
          _list: { label: Voltar }
      new:
        title: Adicionar OS
