contato:
  class: sfDoctrineRouteCollection
  options:
    model:                Contato
    module:               contato
    prefix_path:          /contato
    column:               id
    with_wildcard_routes: true

ordem_servico:
  class: sfDoctrineRouteCollection
  options:
    model:                OrdemServico
    module:               ordem_servico
    prefix_path:          /ordem_servico
    column:               id
    with_wildcard_routes: true

ordem_servico_print:
  url:        /ordem_servico/:id/closeOS
  class:      sfDoctrineRoute
  options:    { model: OrdemServico, type: object }
  param:      { module: ordem_servico, action: closeOS }

ordem_servico_print:
  url:        /ordem_servico/:id/print
  class:      sfDoctrineRoute
  options:    { model: OrdemServico, type: object }
  param:      { module: ordem_servico, action: print }

cliente:
  class: sfDoctrineRouteCollection
  options:
    model:                Cliente
    module:               cliente
    prefix_path:          /cliente
    column:               id
    with_wildcard_routes: true

modelo_peca:
  class: sfDoctrineRouteCollection
  options:
    model:                ModeloPeca
    module:               modelo_peca
    prefix_path:          /modelo_peca
    column:               id
    with_wildcard_routes: true

peca:
  class: sfDoctrineRouteCollection
  options:
    model:                Peca
    module:               peca
    prefix_path:          /peca
    column:               id
    with_wildcard_routes: true

modelo:
  class: sfDoctrineRouteCollection
  options:
    model:                Modelo
    module:               modelo
    prefix_path:          /modelo
    column:               id
    with_wildcard_routes: true

marca:
  class: sfDoctrineRouteCollection
  options:
    model:                Marca
    module:               marca
    prefix_path:          /marca
    column:               id
    with_wildcard_routes: true

autocomplete:
  url: /autocomplete
  param: { module: ordem_servico, action autocomplete }

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: main, action: index }

sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               sf_guard_user
    prefix_path:          /sf_guard_user
    column:               id
    with_wildcard_routes: true

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
