generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ModeloDefeito
    theme:                 adminia
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                Defeitos
    route_prefix:          modelo_defeito
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        defeito_id:   { label: Defeito }
        preco_cartao: { label: Parcelado }
        preco_dinheiro: { label: Dinheiro }
      list:
        title:          Defeitos do Modelo
        display:        [defeito, modelo, preco_cartao, preco_dinheiro]
        sort:           ~
        batch_actions: {}
        object_actions:
          _edit: { label: Editar }
          _delete: { label: Excluir }
        actions:
          _new: { label: "Novo"}
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
