generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Cliente
    theme:                 adminia
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                Clientes
    route_prefix:          cliente
    with_doctrine_route:   true
    actions_base_class:    sfActions
    icon:                 "fa fa-users"

    config:
      actions: ~
      fields:
        created_at:      { label: Data de Criação }
      list:
        title:          Lista de Clientes
        display:        [nome, email, cpf, created_at]
        sort:           ~
        batch_actions:  []
        object_actions:
          _edit: { label: Editar }
          _delete: { label: Excluir }
      filter:
        display: [nome, cpf, email, cidade, estado, filial_id]
      form:    ~
      edit:
        title: Editando Cliente "%%nome%%"
      new:     ~
