<?php

/**
 * ClienteTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cliente');
    }

    public function findClienteByName($name, $limit=10)
    {
      return Doctrine_Query::create()
			   ->from('Cliente c')
         ->where("c.nome LIKE '%{$name}%'")
         ->limit($limit)
         ->execute();
    }
}
