<?php

/**
 * ContatoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContatoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContatoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contato');
    }
}