<?php

/**
 * DefeitoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DefeitoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DefeitoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Defeito');
    }
}