<?php

/**
 * Marca
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    mrjackrj
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Marca extends BaseMarca
{
  public function __toString() {
		return $this->getDescricao();
	}

  public function delete(Doctrine_Connection $conn = null) {
		foreach ($this->getModelos() as $key => $modelo) {
    	$modelo->delete();
    }

		return parent::delete($conn);
	}

  public function getModelos() {
    return ModeloTable::getInstance()->findByMarcaId($this->getId());
  }
}
