<?php

/**
 * ModeloTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModeloTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModeloTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Modelo');
    }

    public function findModeloByName($name, $limit=10)
    {
      return Doctrine_Query::create()
			   ->from('Modelo m')
         ->where("m.nome LIKE '%{$name}%'")
         ->andWhere("m.mostrar_os = 1")
         ->limit($limit)
         ->execute();
    }

    public function findByMarcaIdAndMostrarSiteOrdered($marca_id, $mostrar_site) {
      return Doctrine_Query::create()
			   ->from('Modelo m')
         ->where("m.marca_id = ?", $marca_id)
         ->andWhere('m.mostrar_site = ?', $mostrar_site)
         ->orderBy('m.nome')
         ->execute();
    }
}
