<?php

/**
 * Modelo
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    mrjackrj
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Modelo extends BaseModelo
{
  public function asJson() {
    $modeloPecas = ModeloPecaTable::getInstance()->findByModeloId($this->getId());
    $pecas = array();

    foreach ($modeloPecas as $key => $modeloPeca) {
        $pecas[] = $modeloPeca->asJson();
    }

    return '{"id":'.$this->getId().',"nome":"'.$this->getNome().'","pecas":['.implode(",", $pecas).']}';
  }

  public function delete(Doctrine_Connection $conn = null) {
    foreach ($this->getPecas() as $key => $peca) {
      $modeloPeca = ModeloPecaTable::getInstance()->findByModeloIdAndPecaId($this->getId(), $peca->getId());
      $modeloPeca->delete();
    }

		return parent::delete($conn);
	}

  public function __toString() {
		return $this->getNome();
	}
}
