<?php

/**
 * ModeloDefeitoTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModeloDefeitoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModeloDefeitoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModeloDefeito');
    }

    public function findModeloDefeitoByName($name, $limit=10)
    {
      return Doctrine_Query::create()
         ->select('md.id, CONCAT(mc.descricao, \' - \', m.nome, \' - \', d.nome) as nome')
			   ->from('ModeloDefeito md')
         ->innerJoin('md.Modelo m')
         ->innerJoin('md.Defeito d')
         ->innerJoin('m.Marca mc')
         ->where("m.nome LIKE '%{$name}%'")
         ->orWhere("mc.descricao LIKE '%{$name}%'")
         ->orWhere("d.nome LIKE '%{$name}%'")
         ->limit($limit)
         ->execute();
    }
}
