<?php

/**
 * ModeloDefeito
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    mrjackrj
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ModeloDefeito extends BaseModeloDefeito
{
  public function getDefeito() {
  	return DefeitoTable::getInstance()->findOneById($this->getDefeitoId());
  }

  public function getModelo() {
  	return ModeloTable::getInstance()->findOneById($this->getModeloId());
  }
}
