<?php

/**
 * ModeloDefeitoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModeloDefeitoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModeloDefeitoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModeloDefeito');
    }
}