<?php

/**
 * OrdemServicoListaChecagemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdemServicoListaChecagemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdemServicoListaChecagemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdemServicoListaChecagem');
    }
}