<?php

/**
 * OrdemServicoPecaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdemServicoPecaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdemServicoPecaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdemServicoPeca');
    }
}