<?php

/**
 * Peca
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    mrjackrj
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Peca extends BasePeca
{
  public function __toString() {
		return $this->getNome();
	}
}
