<?php

/**
 * PecaTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PecaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PecaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Peca');
    }

    public function getPecasByModelo($modeloId) {

      return Doctrine_Query::create()
			   ->from('Peca p')
         ->innerJoin('p.ModeloPeca mp')
         ->where("mp.modelo_id = ?", $modeloId)
         ->execute();
    }
}
