generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 adminia
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                Administradores
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    actions_base_class:    sfActions
    icon:                 "fa fa-user"

    config:
      actions: ~
      fields:
        username:       { label: Usuário }
        email_address:  { label: Email }
        first_name:     { label: Nome }
        last_login:     { label: Último login }
        password:       { label: Senha }
        password_again: { label: Repita a senha }
        is_active:      { label: Ativo }
      list:
        title:          Lista de Administradores
        display:        [=username, email_address, first_name, last_login]
        sort:           ~
        batch_actions:  []
        object_actions:
          _edit: { label: Editar }
          _delete: { label: Excluir }
        actions:
          _new: { label: "Novo"}
      filter:
        display:        [username, email_address]
      form:
        class:          sfGuardUserAdminForm
        display:        [first_name, email_address, username, password, password_again, filial_id, groups_list, is_active]
      edit:
        title:          Editar administrador "%%username%%"
      new:
        title:          Adicionar administrador
