generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Defeito
    theme:                 adminia
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                Defeitos
    route_prefix:          defeito
    with_doctrine_route:   true
    actions_base_class:    sfActions
    icon:                 "fa fa-bug"

    config:
      actions: ~
      fields:
        created_at:      { label: Data de Criação }
      list:
        title:          Lista de Defeitos
        display:        [nome, created_at]
        sort:           ~
        batch_actions:  []
        object_actions:
          _edit: { label: Editar }
          _delete: { label: Excluir }
        actions:
          _new: { label: "Novo"}
      filter:
        display: [nome]
      form:    ~
      edit:
        title: Editando Defeito "%%nome%%"
      new:
        title: Adicionar Defeito
