# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: main, action: index }

contato:
  url:   /contato
  param: { module: contato, action: index }

cliente:
  url:   /cliente
  param: { module: main, action: cliente }

precos:
  url:   /precos
  param: { module: precos, action: index }

quemsomos:
  url:   /quemsomos
  param: { module: quemsomos, action: index }

servicos:
  url:   /servicos
  param: { module: servicos, action: index }

aparelhos:
  url:   /aparelhos/:marca
  param: { module: aparelhos, action: index }

modelo_defeito:
  url:  /modelo_defeito/modelo/:modelo_id/defeito/:defeito_id
  param: { module: main, action: modeloDefeito }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
